# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chestnut' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chestnut
  pod 'AlamofireObjectMapper'
  pod 'SDWebImage'
  pod 'GoogleMaps'

  target 'ChestnutTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChestnutUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
